AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.example::spring-lambda-dynamodb-demo3-kike
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SpringLambdaDynamodbDemo3KikeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: articles
      Environment:
        Variables:
          AWS_REGION: us-east-1
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: articles
      AttributeDefinitions:
        - AttributeName: articleId
          AttributeType: S
      KeySchema:
        - AttributeName: articleId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  SpringLambdaDynamodbDemo3KikeApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringLambdaDynamodbDemo3KikeApi
